Last login: Mon Apr  8 11:03:41 on ttys000
➜  ~ cd Documents
➜  Documents cd Javascript
cd: no such file or directory: Javascript
➜  Documents cd Javascript_Exercises 
➜  Javascript_Exercises git:(master) ✗ node fff_javascriptp2.js
➜  Javascript_Exercises git:(master) ✗ node fff_javascriptp2.js
undefined
➜  Javascript_Exercises git:(master) ✗ node fff_javascriptp2.js
undefined
mordoring most be a dread!
➜  Javascript_Exercises git:(master) ✗ node fff_javascriptp2.js
undefined
➜  Javascript_Exercises git:(master) ✗ node fff_javascriptp2.js
Object [global] {
  DTRACE_NET_SERVER_CONNECTION: [Function],
  DTRACE_NET_STREAM_END: [Function],
  DTRACE_HTTP_SERVER_REQUEST: [Function],
  DTRACE_HTTP_SERVER_RESPONSE: [Function],
  DTRACE_HTTP_CLIENT_REQUEST: [Function],
  DTRACE_HTTP_CLIENT_RESPONSE: [Function],
  global: [Circular],
  process:
   process {
     title: 'node',
     version: 'v10.15.3',
     versions:
      { http_parser: '2.8.0',
        node: '10.15.3',
        v8: '6.8.275.32-node.51',
        uv: '1.23.2',
        zlib: '1.2.11',
        ares: '1.15.0',
        modules: '64',
        nghttp2: '1.34.0',
        napi: '3',
        openssl: '1.1.0j',
        icu: '62.1',
        unicode: '11.0',
        cldr: '33.1',
        tz: '2018e' },
     arch: 'x64',
     platform: 'darwin',
     release:
      { name: 'node',
        lts: 'Dubnium',
        sourceUrl:
         'https://nodejs.org/download/release/v10.15.3/node-v10.15.3.tar.gz',
        headersUrl:
         'https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz' },
     argv:
      [ '/usr/local/bin/node',
        '/Users/dawitghebremedhin/Documents/Javascript_Exercises/fff_javascriptp2.js' ],
     execArgv: [],
     env:
      { TMPDIR: '/var/folders/43/sv3x70_j7hv9vh5sqd0s6nww0000gn/T/',
        XPC_FLAGS: '0x0',
        Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.adAcVrOpP3/Render',
        TERM_PROGRAM_VERSION: '404',
        LC_CTYPE: 'UTF-8',
        TERM_PROGRAM: 'Apple_Terminal',
        XPC_SERVICE_NAME: '0',
        TERM_SESSION_ID: '4B79CEFD-874D-4749-BB0F-5DCC4868F20B',
        SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.YY1gbMUHxB/Listeners',
        TERM: 'xterm-256color',
        SHELL: '/bin/zsh',
        HOME: '/Users/dawitghebremedhin',
        LOGNAME: 'dawitghebremedhin',
        USER: 'dawitghebremedhin',
        PATH: '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
        SHLVL: '1',
        PWD: '/Users/dawitghebremedhin/Documents/Javascript_Exercises',
        OLDPWD: '/Users/dawitghebremedhin/Documents',
        ZSH: '/Users/dawitghebremedhin/.oh-my-zsh',
        PAGER: 'less',
        LESS: '-R',
        LSCOLORS: 'Gxfxcxdxbxegedabagacad',
        _: '/usr/local/bin/node',
        __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0' },
     pid: 26912,
     features:
      { debug: false,
        uv: true,
        ipv6: true,
        tls_alpn: true,
        tls_sni: true,
        tls_ocsp: true,
        tls: true },
     ppid: 26772,
     execPath: '/usr/local/bin/node',
     debugPort: 9229,
     _debugProcess: [Function: _debugProcess],
     _debugEnd: [Function: _debugEnd],
     _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
     _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
     abort: [Function: abort],
     chdir: [Function: chdir],
     umask: [Function: umask],
     _getActiveRequests: [Function: _getActiveRequests],
     _getActiveHandles: [Function: _getActiveHandles],
     _kill: [Function: _kill],
     cwd: [Function: cwd],
     dlopen: [Function: dlopen],
     reallyExit: [Function: reallyExit],
     uptime: [Function: uptime],
     getuid: [Function: getuid],
     geteuid: [Function: geteuid],
     getgid: [Function: getgid],
     getegid: [Function: getegid],
     getgroups: [Function: getgroups],
     _rawDebug: [Function],
     moduleLoadList:
      [ 'Internal Binding module_wrap',
        'Binding contextify',
        'Internal Binding worker',
        'NativeModule events',
        'NativeModule internal/async_hooks',
        'NativeModule internal/errors',
        'Binding uv',
        'Binding buffer',
        'Binding async_wrap',
        'Internal Binding async_wrap',
        'Binding config',
        'Binding icu',
        'NativeModule util',
        'NativeModule internal/util/inspect',
        'Binding util',
        'NativeModule internal/util',
        'Binding constants',
        'Internal Binding types',
        'NativeModule internal/util/types',
        'NativeModule internal/validators',
        'NativeModule internal/encoding',
        'Internal Binding icu',
        'NativeModule buffer',
        'NativeModule internal/buffer',
        'NativeModule internal/process/per_thread',
        'NativeModule internal/process/main_thread_only',
        'NativeModule internal/process/stdio',
        'NativeModule assert',
        'NativeModule internal/assert',
        'NativeModule fs',
        'NativeModule path',
        'NativeModule internal/constants',
        'Binding fs',
        'NativeModule internal/fs/streams',
        'NativeModule internal/fs/utils',
        'NativeModule stream',
        'NativeModule internal/streams/pipeline',
        'NativeModule internal/streams/end-of-stream',
        'NativeModule internal/streams/legacy',
        'NativeModule _stream_readable',
        'NativeModule internal/streams/buffer_list',
        'NativeModule internal/streams/destroy',
        'NativeModule internal/streams/state',
        'NativeModule _stream_writable',
        'NativeModule _stream_duplex',
        'NativeModule _stream_transform',
        'NativeModule _stream_passthrough',
        'NativeModule internal/url',
        'NativeModule internal/querystring',
        'Binding url',
        'NativeModule internal/process/warning',
        'NativeModule internal/process/next_tick',
        'NativeModule internal/process/promises',
        'Internal Binding util',
        'NativeModule internal/fixed_queue',
        'Binding performance',
        'Binding trace_events',
        'NativeModule internal/inspector_async_hook',
        'Binding inspector',
        'NativeModule internal/options',
        'Internal Binding options',
        'NativeModule timers',
        'Binding timer_wrap',
        'NativeModule internal/linkedlist',
        'NativeModule internal/timers',
        'NativeModule console',
        'Binding tty_wrap',
        'Internal Binding tty_wrap',
        'NativeModule tty',
        'NativeModule net',
        'NativeModule internal/net',
        'Binding stream_wrap',
        'Binding tcp_wrap',
        'Binding pipe_wrap',
        'NativeModule internal/stream_base_commons',
        'Internal Binding stream_wrap',
        'Internal Binding uv',
        'NativeModule internal/tty',
        'Binding signal_wrap',
        'NativeModule internal/modules/cjs/loader',
        'NativeModule vm',
        'NativeModule url',
        'NativeModule internal/safe_globals',
        'NativeModule internal/modules/cjs/helpers' ],
     binding: [Function: binding],
     _linkedBinding: [Function: _linkedBinding],
     _events:
      [Object: null prototype] {
        newListener: [Function],
        removeListener: [Function],
        warning: [Function],
        SIGWINCH: [Array] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _fatalException: [Function],
     domain: null,
     _exiting: false,
     assert: [Function: deprecated],
     config: { target_defaults: [Object], variables: [Object] },
     setUncaughtExceptionCaptureCallback: [Function],
     hasUncaughtExceptionCaptureCallback: [Function],
     emitWarning: [Function],
     nextTick: [Function: nextTick],
     _tickCallback: [Function: _tickCallback],
     stdout: [Getter],
     stderr: [Getter],
     stdin: [Getter],
     openStdin: [Function],
     initgroups: [Function: initgroups],
     setegid: [Function: setegid],
     seteuid: [Function: seteuid],
     setgid: [Function: setgid],
     setuid: [Function: setuid],
     setgroups: [Function: setgroups],
     hrtime: { [Function: hrtime] bigint: [Function] },
     cpuUsage: [Function: cpuUsage],
     memoryUsage: [Function: memoryUsage],
     exit: [Function],
     kill: [Function],
     argv0: 'node',
     allowedNodeEnvironmentFlags: [Getter/Setter],
     mainModule:
      Module {
        id: '.',
        exports: {},
        parent: null,
        filename:
         '/Users/dawitghebremedhin/Documents/Javascript_Exercises/fff_javascriptp2.js',
        loaded: false,
        children: [],
        paths: [Array] } },
  Buffer:
   { [Function: Buffer]
     poolSize: 8192,
     from: [Function: from],
     of: [Function: of],
     alloc: [Function: alloc],
     allocUnsafe: [Function: allocUnsafe],
     allocUnsafeSlow: [Function: allocUnsafeSlow],
     isBuffer: [Function: isBuffer],
     compare: [Function: compare],
     isEncoding: [Function: isEncoding],
     concat: [Function: concat],
     byteLength: [Function: byteLength],
     [Symbol(kIsEncodingSymbol)]: [Function: isEncoding] },
  clearImmediate: [Function: clearImmediate],
  clearInterval: [Function: clearInterval],
  clearTimeout: [Function: clearTimeout],
  setImmediate:
   { [Function: setImmediate] [Symbol(util.promisify.custom)]: [Function] },
  setInterval: [Function: setInterval],
  setTimeout:
   { [Function: setTimeout] [Symbol(util.promisify.custom)]: [Function] } }